ALTER TYPE "PigEventType" ADD VALUE IF NOT EXISTS 'TEETH_CLIPPING';
ALTER TYPE "PigEventType" ADD VALUE IF NOT EXISTS 'TAIL_DOCKING';
ALTER TYPE "PigEventType" ADD VALUE IF NOT EXISTS 'CASTRATION';
ALTER TYPE "PigEventType" ADD VALUE IF NOT EXISTS 'IRON_INJECTION';
